### ISSUE TITLE
Don't use underscore in Enum names

### ISSUE THREAD

**Issue by pelikhan** [lionyhw/pxt-cutebot#9]
See naming conventions: https://makecode.com/extensions/naming-conventions
https://github.com/lionyhw/pxt-cutebot/blob/8e4264aa62a8358fc6e60f4563cfc4e3357f9866/cutebot.ts#L69

**Comment by abchatra** [comment]
Just to reiterate use camelCase and not snake_case.

**Comment by pelikhan** [comment]
![image](https://user-images.githubusercontent.com/4175913/56914568-4bf57a80-6a69-11e9-8ccc-ec6dba1ef58f.png)
